module ActiveRecord
  class Schema
    def self.[]: (untyped version) -> ActiveRecord::Migration::Current
  end

  class Migration
    class Current
      def define: (version: untyped) { () [self: instance] -> void } -> void

      %a{siggen:
        # In schema.rb, this model is declared as:
        #
        # ```ruby
        # <%= ___source %>
        # ```
        class <%= table_name.classify %>
          include GeneratedAttributeMethods
        end
      }
      def create_table: (untyped table_name, **untyped options) { (ActiveRecord::ConnectionAdapters::ColumnMethods t) -> void } -> void
    end
  end

  module ConnectionAdapters
    module ColumnMethods
        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::Integer<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::Integer<%= "?" unless options[:null] == false %>, ::Integer<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::Integer<%= "?" unless options[:null] == false %>, ::Integer<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::Integer<%= "?" unless options[:null] == false %>, ::Integer<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::Integer<%= "?" unless options[:null] == false %>, ::Integer<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::Integer<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def bitint: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::String<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::String<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def binary: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> bool<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (bool<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [bool<%= "?" unless options[:null] == false %>, bool<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> bool<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [bool<%= "?" unless options[:null] == false %>, bool<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> bool<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [bool<%= "?" unless options[:null] == false %>, bool<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> bool<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [bool<%= "?" unless options[:null] == false %>, bool<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> bool<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def boolean: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::Date<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::Date<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::Date<%= "?" unless options[:null] == false %>, ::Date<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::Date<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::Date<%= "?" unless options[:null] == false %>, ::Date<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::Date<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::Date<%= "?" unless options[:null] == false %>, ::Date<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::Date<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::Date<%= "?" unless options[:null] == false %>, ::Date<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::Date<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def date: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def datetime: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::BigDecimal<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::BigDecimal<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::BigDecimal<%= "?" unless options[:null] == false %>, ::BigDecimal<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::BigDecimal<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::BigDecimal<%= "?" unless options[:null] == false %>, ::BigDecimal<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::BigDecimal<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::BigDecimal<%= "?" unless options[:null] == false %>, ::BigDecimal<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::BigDecimal<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::BigDecimal<%= "?" unless options[:null] == false %>, ::BigDecimal<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::BigDecimal<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def decimal: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::Float<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::Float<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::Float<%= "?" unless options[:null] == false %>, ::Float<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::Float<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::Float<%= "?" unless options[:null] == false %>, ::Float<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::Float<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::Float<%= "?" unless options[:null] == false %>, ::Float<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::Float<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::Float<%= "?" unless options[:null] == false %>, ::Float<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::Float<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def float: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::Integer<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::Integer<%= "?" unless options[:null] == false %>, ::Integer<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::Integer<%= "?" unless options[:null] == false %>, ::Integer<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::Integer<%= "?" unless options[:null] == false %>, ::Integer<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::Integer<%= "?" unless options[:null] == false %>, ::Integer<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::Integer<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def integer: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> untyped<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (untyped<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [untyped<%= "?" unless options[:null] == false %>, untyped<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> untyped<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [untyped<%= "?" unless options[:null] == false %>, untyped<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> untyped<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [untyped<%= "?" unless options[:null] == false %>, untyped<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> untyped<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [untyped<%= "?" unless options[:null] == false %>, untyped<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> untyped<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def json: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::String<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::String<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def string: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::String<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::String<%= "?" unless options[:null] == false %>, ::String<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::String<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def text: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def time: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>, ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def timestamp: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          <% map = [[:bitint, "::Integer"], [:binary, "::String"], [:boolean, "bool"], [:date, "::Date"], [:datetime, "::ActiveSupport::TimeWithZone"], [:decimal, "::BigDecimal"], [:float, "::Float"], [:integer, "::Integer"], [:json, "untyped"], [:string, "::String"], [:text, "::String"], [:time, "::ActiveSupport::TimeWithZone"], [:timestamp, "::ActiveSupport::TimeWithZone"], [:virtual, "_"]].to_h %>
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> <%= map[options[:type]] %><%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (<%= map[options[:type]] %><%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                def <%= name %>_came_from_user?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Query"] %>
                def <%= name %>?: () -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_changed?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_change: () -> [<%= map[options[:type]] %><%= "?" unless options[:null] == false %>, <%= map[options[:type]] %><%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_will_change!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_was: () -> <%= map[options[:type]] %><%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previous_change: () -> [<%= map[options[:type]] %><%= "?" unless options[:null] == false %>, <%= map[options[:type]] %><%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def <%= name %>_previously_was: () -> <%= map[options[:type]] %><%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def restore_<%= name %>!: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveModel::Dirty"] %>
                def clear_<%= name %>_change: () -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute?"] %>
                def saved_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#saved_change_to_attribute"] %>
                def saved_change_to_<%= name %>: () -> [<%= map[options[:type]] %><%= "?" unless options[:null] == false %>, <%= map[options[:type]] %><%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_before_last_save"] %>
                def <%= name %>_before_last_save: () -> <%= map[options[:type]] %><%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#will_save_change_to_attribute?"] %>
                def will_save_change_to_<%= name %>?: (?from: untyped, ?to: untyped) -> bool

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_change_to_be_saved: () -> [<%= map[options[:type]] %><%= "?" unless options[:null] == false %>, <%= map[options[:type]] %><%= "?" unless options[:null] == false %>]?

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Dirty#attribute_change_to_be_saved"] %>
                def <%= name %>_in_database: () -> <%= map[options[:type]] %><%= "?" unless options[:null] == false %>
              <% end %>
            end
          end
        }
        def virtual: (*Array[untyped] names, **untyped options) -> void

    end

    class TableDefinition
      include ColumnMethods
    end
  end
end