module ActiveRecord
  class Schema
    def self.[]: (untyped version) -> ActiveRecord::Migration::Current
  end

  class Migration
    class Current
      def define: (version: untyped) { () [self: instance] -> void } -> void

      %a{siggen:
        # In schema.rb, this model is declared as:
        #
        # ```ruby
        # <%= ___source %>
        # ```
        class <%= table_name.classify %>
          include GeneratedAttributeMethods
        end
      }
      def create_table: (untyped table_name, **untyped options) { (ActiveRecord::ConnectionAdapters::ColumnMethods t) -> void } -> void
    end
  end

  module ConnectionAdapters
    module ColumnMethods
        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::Integer<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def bitint: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::String<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def binary: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> bool<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (bool<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def boolean: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::Date<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::Date<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def date: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def datetime: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::BigDecimal<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::BigDecimal<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def decimal: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::Float<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::Float<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def float: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::Integer<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::Integer<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def integer: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> untyped<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (untyped<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def json: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::String<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def string: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::String<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::String<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def text: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def time: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> ::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (::ActiveSupport::TimeWithZone<%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def timestamp: (*Array[untyped] names, **untyped options) -> void

        %a{siggen:
          <% map = [[:bitint, "::Integer"], [:binary, "::String"], [:boolean, "bool"], [:date, "::Date"], [:datetime, "::ActiveSupport::TimeWithZone"], [:decimal, "::BigDecimal"], [:float, "::Float"], [:integer, "::Integer"], [:json, "untyped"], [:string, "::String"], [:text, "::String"], [:time, "::ActiveSupport::TimeWithZone"], [:timestamp, "::ActiveSupport::TimeWithZone"], [:virtual, "_"]].to_h %>
          class <%= create_table.table_name.classify %>
            module GeneratedAttributeMethods
              <% names.each do |name| %>
                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Read#read_attribute"] %>
                def <%= name %>: () -> <%= map[options[:type]] %><%= "?" unless options[:null] == false %>

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::Write#write_attribute"] %>
                def <%= name %>=: (<%= map[options[:type]] %><%= "?" unless options[:null] == false %> value) -> void

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_before_type_cast"] %>
                def <%= name %>_before_type_cast: () -> untyped

                # ```ruby
                # <%= ___source %>
                # ```
                # <%= ___comment_of["ActiveRecord::AttributeMethods::BeforeTypeCast#read_attribute_for_database"] %>
                def <%= name %>_for_database: () -> untyped
              <% end %>
            end
          end
        }
        def virtual: (*Array[untyped] names, **untyped options) -> void

    end

    class TableDefinition
      include ColumnMethods
    end
  end
end