module ActiveSupport
  class TimeWithZone
  end

  class TestCase < ::Minitest::Test
    def self.test: (::String name) { () [self: ::Minitest::Test] -> void } -> void
    def self.fixtures: (*untyped) -> void
  end
end

module ActiveRecord
  class Base
    def self.first: () -> instance?
    def self.first!: () -> instance
    def self.find_by!: (**untyped) -> instance
    def save!: (**untyped options) -> bool
  end
end

class ApplicationRecord < ::ActiveRecord::Base
end

class PostTest < ::ActiveSupport::TestCase
end

class AccountAccountCodeTest < ::ActiveSupport::TestCase
end

class AccountIdAliasTest < ::ActiveSupport::TestCase
end

class ArticleIdTest < ::ActiveSupport::TestCase
end

class PostTagIdFalseTest < ::ActiveSupport::TestCase
end

class PostTagPostIdTest < ::ActiveSupport::TestCase
end

class PostTagTagNameTest < ::ActiveSupport::TestCase
end

class TaggingIdTest < ::ActiveSupport::TestCase
end

class TaggingPostIdTest < ::ActiveSupport::TestCase
end

class TaggingTagIdTest < ::ActiveSupport::TestCase
end
