module ActiveSupport
  class TestCase < ::Minitest::Test
    def self.test: (::String name) { () [self: ::Minitest::Test] -> void } -> void
    def self.fixtures: (*untyped) -> void
  end
end

module ActiveRecord
  class Base
    def self.find_by!: (untyped) -> untyped
  end
end
