module ActiveSupport
  class TestCase < ::Minitest::Test
    def self.test: (::String name) { () [self: ::Minitest::Test] -> void } -> void
    def self.fixtures: (*untyped) -> void
  end
end

class ApplicationRecord < ::ActiveRecord::Base
end
