class Account < ApplicationRecord
end

class ApplicationRecord < ActiveRecord::Base
end

class Article < ApplicationRecord
end

class Author < ApplicationRecord
end

class PostTag < ApplicationRecord
end

class Post < ApplicationRecord
end

class Profile < ApplicationRecord
end

class Tagging < ApplicationRecord
end
