# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "accounts", primary_key: "account_code", id: :string, force: :cascade do |t|
#   t.string "name"
# end
# ```
class Account < ::ApplicationRecord
  module GeneratedAttributeMethods
    def account_code: () -> ::String

    def account_code=: (::String value) -> void

    def account_code_before_type_cast: () -> untyped

    def account_code_for_database: () -> untyped

    def account_code_came_from_user?: () -> bool

    def account_code?: () -> bool

    def account_code_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def account_code_changed?: (?from: untyped, ?to: untyped) -> bool

    def account_code_change: () -> [ ::String, ::String ]?

    def account_code_will_change!: () -> void

    def account_code_was: () -> ::String

    def account_code_previous_change: () -> [ ::String, ::String ]?

    def account_code_previously_was: () -> ::String

    def restore_account_code!: () -> void

    def clear_account_code_change: () -> void

    def saved_change_to_account_code?: (?from: untyped, ?to: untyped) -> bool

    def saved_change_to_account_code: () -> [ ::String, ::String ]?

    def account_code_before_last_save: () -> ::String

    def will_save_change_to_account_code?: (?from: untyped, ?to: untyped) -> bool

    def account_code_change_to_be_saved: () -> [ ::String, ::String ]?

    def account_code_in_database: () -> ::String

    def id: () -> ::String

    def id=: (::String value) -> void

    def id_before_type_cast: () -> untyped

    def id_for_database: () -> untyped

    def id_came_from_user?: () -> bool

    def id?: () -> bool

    def id_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def id_changed?: (?from: untyped, ?to: untyped) -> bool

    def id_change: () -> [ ::String, ::String ]?

    def id_will_change!: () -> void

    def id_was: () -> ::String

    def id_previous_change: () -> [ ::String, ::String ]?

    def id_previously_was: () -> ::String

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def saved_change_to_id?: (?from: untyped, ?to: untyped) -> bool

    def saved_change_to_id: () -> [ ::String, ::String ]?

    def id_before_last_save: () -> ::String

    def will_save_change_to_id?: (?from: untyped, ?to: untyped) -> bool

    def id_change_to_be_saved: () -> [ ::String, ::String ]?

    def id_in_database: () -> ::String

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name: () -> ::String?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name=: (::String? value) -> void

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_before_type_cast: () -> untyped

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_for_database: () -> untyped

    # ```ruby
    # t.string "name"
    # ```
    %a{rbs:test:target}
    def name_came_from_user?: () -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name?: () -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_will_change!: () -> void

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_was: () -> ::String?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_previous_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_previously_was: () -> ::String?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def restore_name!: () -> void

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def clear_name_change: () -> void

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_name?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_name: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_before_last_save: () -> ::String?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_name?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_change_to_be_saved: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_in_database: () -> ::String?
  end
  include GeneratedAttributeMethods

  def self.create: (?name: ::String) -> instance
                 | (Array[untyped]) -> Array[instance]
end

# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "articles", id: :string, force: :cascade do |t|
#   t.string "name"
# end
# ```
class Article < ::ApplicationRecord
  module GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String value) -> void

    def id_before_type_cast: () -> untyped

    def id_for_database: () -> untyped

    def id_came_from_user?: () -> bool

    def id?: () -> bool

    def id_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def id_changed?: (?from: untyped, ?to: untyped) -> bool

    def id_change: () -> [ ::String, ::String ]?

    def id_will_change!: () -> void

    def id_was: () -> ::String

    def id_previous_change: () -> [ ::String, ::String ]?

    def id_previously_was: () -> ::String

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def saved_change_to_id?: (?from: untyped, ?to: untyped) -> bool

    def saved_change_to_id: () -> [ ::String, ::String ]?

    def id_before_last_save: () -> ::String

    def will_save_change_to_id?: (?from: untyped, ?to: untyped) -> bool

    def id_change_to_be_saved: () -> [ ::String, ::String ]?

    def id_in_database: () -> ::String

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name: () -> ::String?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name=: (::String? value) -> void

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_before_type_cast: () -> untyped

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_for_database: () -> untyped

    # ```ruby
    # t.string "name"
    # ```
    %a{rbs:test:target}
    def name_came_from_user?: () -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name?: () -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_will_change!: () -> void

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_was: () -> ::String?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_previous_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_previously_was: () -> ::String?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def restore_name!: () -> void

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def clear_name_change: () -> void

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_name?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_name: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_before_last_save: () -> ::String?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_name?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_change_to_be_saved: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "name"
    # ```
    #
    %a{rbs:test:target}
    def name_in_database: () -> ::String?
  end
  include GeneratedAttributeMethods

  def self.create: (?name: ::String) -> instance
                 | (Array[untyped]) -> Array[instance]
end

# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "post_tags", id: false, force: :cascade do |t|
#   t.integer "post_id", null: false
#   t.string "tag_name", null: false
# end
# ```
class PostTag < ::ApplicationRecord
  module GeneratedAttributeMethods
    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id: () -> ::Integer

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id=: (::Integer value) -> void

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_before_type_cast: () -> untyped

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_for_database: () -> untyped

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    %a{rbs:test:target}
    def post_id_came_from_user?: () -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id?: () -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_change: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_will_change!: () -> void

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_was: () -> ::Integer

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_previous_change: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_previously_was: () -> ::Integer

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def restore_post_id!: () -> void

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def clear_post_id_change: () -> void

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_post_id?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_post_id: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_before_last_save: () -> ::Integer

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_post_id?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_change_to_be_saved: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_in_database: () -> ::Integer

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name: () -> ::String

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name=: (::String value) -> void

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_before_type_cast: () -> untyped

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_for_database: () -> untyped

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    %a{rbs:test:target}
    def tag_name_came_from_user?: () -> bool

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name?: () -> bool

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_change: () -> [ ::String, ::String ]?

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_will_change!: () -> void

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_was: () -> ::String

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_previous_change: () -> [ ::String, ::String ]?

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_previously_was: () -> ::String

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def restore_tag_name!: () -> void

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def clear_tag_name_change: () -> void

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_tag_name?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_tag_name: () -> [ ::String, ::String ]?

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_before_last_save: () -> ::String

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_tag_name?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_change_to_be_saved: () -> [ ::String, ::String ]?

    # ```ruby
    # t.string "tag_name", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_name_in_database: () -> ::String
  end
  include GeneratedAttributeMethods

  def self.create: (?post_id: ::Integer, ?tag_name: ::String) -> instance
                 | (Array[untyped]) -> Array[instance]
end

# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "posts", force: :cascade do |t|
#   t.text "body"
#   t.datetime "created_at", null: false
#   t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
#   t.integer "likes_count"
#   t.json "metadata"
#   t.decimal "price"
#   t.boolean "published"
#   t.date "published_on"
#   t.float "rating"
#   t.virtual "slug", type: :string, as: "lower(title)", stored: true
#   t.time "start_time"
#   t.binary "thumbnail"
#   t.string "title"
#   t.datetime "updated_at", null: false
#   t.bigint "views_count"
# end
# ```
class Post < ::ApplicationRecord
  module GeneratedAttributeMethods
    def id: () -> Integer?

    def id=: (Integer? value) -> void

    def id_before_type_cast: () -> untyped

    def id_for_database: () -> untyped

    def id_came_from_user?: () -> bool

    def id?: () -> bool

    def id_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def id_changed?: (?from: untyped, ?to: untyped) -> bool

    def id_change: () -> [ Integer?, Integer? ]?

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previous_change: () -> [ Integer?, Integer? ]?

    def id_previously_was: () -> Integer?

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def saved_change_to_id?: (?from: untyped, ?to: untyped) -> bool

    def saved_change_to_id: () -> [ Integer?, Integer? ]?

    def id_before_last_save: () -> Integer?

    def will_save_change_to_id?: (?from: untyped, ?to: untyped) -> bool

    def id_change_to_be_saved: () -> [ Integer?, Integer? ]?

    def id_in_database: () -> Integer?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body: () -> ::String?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body=: (::String? value) -> void

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_before_type_cast: () -> untyped

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_for_database: () -> untyped

    # ```ruby
    # t.text "body"
    # ```
    %a{rbs:test:target}
    def body_came_from_user?: () -> bool

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body?: () -> bool

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_will_change!: () -> void

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_was: () -> ::String?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_previous_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_previously_was: () -> ::String?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def restore_body!: () -> void

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def clear_body_change: () -> void

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_body?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_body: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_before_last_save: () -> ::String?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_body?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_change_to_be_saved: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.text "body"
    # ```
    #
    %a{rbs:test:target}
    def body_in_database: () -> ::String?

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at=: (::ActiveSupport::TimeWithZone | ::Time value) -> void

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_for_database: () -> untyped

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    %a{rbs:test:target}
    def created_at_came_from_user?: () -> bool

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at?: () -> bool

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone ]?

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_will_change!: () -> void

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_was: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_previous_change: () -> [ ::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone ]?

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def restore_created_at!: () -> void

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def clear_created_at_change: () -> void

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_created_at?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_created_at: () -> [ ::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone ]?

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_created_at?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_change_to_be_saved: () -> [ ::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone ]?

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count: () -> ::Integer?

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count=: (::Integer? value) -> void

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_before_type_cast: () -> untyped

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_for_database: () -> untyped

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    %a{rbs:test:target}
    def engagement_count_came_from_user?: () -> bool

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count?: () -> bool

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_change: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_will_change!: () -> void

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_was: () -> ::Integer?

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_previous_change: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_previously_was: () -> ::Integer?

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def restore_engagement_count!: () -> void

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def clear_engagement_count_change: () -> void

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_engagement_count?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_engagement_count: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_before_last_save: () -> ::Integer?

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_engagement_count?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_change_to_be_saved: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.virtual "engagement_count", type: :integer, as: "likes_count + views_count", stored: true
    # ```
    #
    %a{rbs:test:target}
    def engagement_count_in_database: () -> ::Integer?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count: () -> ::Integer?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count=: (::Integer? value) -> void

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_before_type_cast: () -> untyped

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_for_database: () -> untyped

    # ```ruby
    # t.integer "likes_count"
    # ```
    %a{rbs:test:target}
    def likes_count_came_from_user?: () -> bool

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count?: () -> bool

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_change: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_will_change!: () -> void

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_was: () -> ::Integer?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_previous_change: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_previously_was: () -> ::Integer?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def restore_likes_count!: () -> void

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def clear_likes_count_change: () -> void

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_likes_count?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_likes_count: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_before_last_save: () -> ::Integer?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_likes_count?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_change_to_be_saved: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.integer "likes_count"
    # ```
    #
    %a{rbs:test:target}
    def likes_count_in_database: () -> ::Integer?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata: () -> untyped?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata=: (untyped? value) -> void

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_before_type_cast: () -> untyped

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_for_database: () -> untyped

    # ```ruby
    # t.json "metadata"
    # ```
    %a{rbs:test:target}
    def metadata_came_from_user?: () -> bool

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata?: () -> bool

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_change: () -> [ untyped?, untyped? ]?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_will_change!: () -> void

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_was: () -> untyped?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_previous_change: () -> [ untyped?, untyped? ]?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_previously_was: () -> untyped?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def restore_metadata!: () -> void

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def clear_metadata_change: () -> void

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_metadata?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_metadata: () -> [ untyped?, untyped? ]?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_before_last_save: () -> untyped?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_metadata?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_change_to_be_saved: () -> [ untyped?, untyped? ]?

    # ```ruby
    # t.json "metadata"
    # ```
    #
    %a{rbs:test:target}
    def metadata_in_database: () -> untyped?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price: () -> ::BigDecimal?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price=: (::BigDecimal? value) -> void

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_before_type_cast: () -> untyped

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_for_database: () -> untyped

    # ```ruby
    # t.decimal "price"
    # ```
    %a{rbs:test:target}
    def price_came_from_user?: () -> bool

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price?: () -> bool

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_change: () -> [ ::BigDecimal?, ::BigDecimal? ]?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_will_change!: () -> void

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_was: () -> ::BigDecimal?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_previous_change: () -> [ ::BigDecimal?, ::BigDecimal? ]?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_previously_was: () -> ::BigDecimal?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def restore_price!: () -> void

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def clear_price_change: () -> void

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_price?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_price: () -> [ ::BigDecimal?, ::BigDecimal? ]?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_before_last_save: () -> ::BigDecimal?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_price?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_change_to_be_saved: () -> [ ::BigDecimal?, ::BigDecimal? ]?

    # ```ruby
    # t.decimal "price"
    # ```
    #
    %a{rbs:test:target}
    def price_in_database: () -> ::BigDecimal?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published: () -> bool?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published=: (bool? value) -> void

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_before_type_cast: () -> untyped

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_for_database: () -> untyped

    # ```ruby
    # t.boolean "published"
    # ```
    %a{rbs:test:target}
    def published_came_from_user?: () -> bool

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published?: () -> bool

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_change: () -> [ bool?, bool? ]?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_will_change!: () -> void

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_was: () -> bool?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_previous_change: () -> [ bool?, bool? ]?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_previously_was: () -> bool?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def restore_published!: () -> void

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def clear_published_change: () -> void

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_published?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_published: () -> [ bool?, bool? ]?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_before_last_save: () -> bool?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_published?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_change_to_be_saved: () -> [ bool?, bool? ]?

    # ```ruby
    # t.boolean "published"
    # ```
    #
    %a{rbs:test:target}
    def published_in_database: () -> bool?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on: () -> ::Date?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on=: (::Date? value) -> void

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_before_type_cast: () -> untyped

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_for_database: () -> untyped

    # ```ruby
    # t.date "published_on"
    # ```
    %a{rbs:test:target}
    def published_on_came_from_user?: () -> bool

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on?: () -> bool

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_change: () -> [ ::Date?, ::Date? ]?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_will_change!: () -> void

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_was: () -> ::Date?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_previous_change: () -> [ ::Date?, ::Date? ]?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_previously_was: () -> ::Date?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def restore_published_on!: () -> void

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def clear_published_on_change: () -> void

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_published_on?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_published_on: () -> [ ::Date?, ::Date? ]?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_before_last_save: () -> ::Date?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_published_on?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_change_to_be_saved: () -> [ ::Date?, ::Date? ]?

    # ```ruby
    # t.date "published_on"
    # ```
    #
    %a{rbs:test:target}
    def published_on_in_database: () -> ::Date?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating: () -> ::Float?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating=: (::Float? value) -> void

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_before_type_cast: () -> untyped

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_for_database: () -> untyped

    # ```ruby
    # t.float "rating"
    # ```
    %a{rbs:test:target}
    def rating_came_from_user?: () -> bool

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating?: () -> bool

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_change: () -> [ ::Float?, ::Float? ]?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_will_change!: () -> void

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_was: () -> ::Float?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_previous_change: () -> [ ::Float?, ::Float? ]?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_previously_was: () -> ::Float?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def restore_rating!: () -> void

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def clear_rating_change: () -> void

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_rating?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_rating: () -> [ ::Float?, ::Float? ]?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_before_last_save: () -> ::Float?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_rating?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_change_to_be_saved: () -> [ ::Float?, ::Float? ]?

    # ```ruby
    # t.float "rating"
    # ```
    #
    %a{rbs:test:target}
    def rating_in_database: () -> ::Float?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug: () -> ::String?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug=: (::String? value) -> void

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_before_type_cast: () -> untyped

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_for_database: () -> untyped

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    %a{rbs:test:target}
    def slug_came_from_user?: () -> bool

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug?: () -> bool

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_will_change!: () -> void

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_was: () -> ::String?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_previous_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_previously_was: () -> ::String?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def restore_slug!: () -> void

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def clear_slug_change: () -> void

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_slug?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_slug: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_before_last_save: () -> ::String?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_slug?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_change_to_be_saved: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.virtual "slug", type: :string, as: "lower(title)", stored: true
    # ```
    #
    %a{rbs:test:target}
    def slug_in_database: () -> ::String?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time: () -> ::ActiveSupport::TimeWithZone?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time=: ((::ActiveSupport::TimeWithZone | ::Time)? value) -> void

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_before_type_cast: () -> untyped

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_for_database: () -> untyped

    # ```ruby
    # t.time "start_time"
    # ```
    %a{rbs:test:target}
    def start_time_came_from_user?: () -> bool

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time?: () -> bool

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_will_change!: () -> void

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_was: () -> ::ActiveSupport::TimeWithZone?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_previous_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_previously_was: () -> ::ActiveSupport::TimeWithZone?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def restore_start_time!: () -> void

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def clear_start_time_change: () -> void

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_start_time?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_start_time: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_start_time?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_change_to_be_saved: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]?

    # ```ruby
    # t.time "start_time"
    # ```
    #
    %a{rbs:test:target}
    def start_time_in_database: () -> ::ActiveSupport::TimeWithZone?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail: () -> ::String?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail=: (::String? value) -> void

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_before_type_cast: () -> untyped

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_for_database: () -> untyped

    # ```ruby
    # t.binary "thumbnail"
    # ```
    %a{rbs:test:target}
    def thumbnail_came_from_user?: () -> bool

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail?: () -> bool

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_will_change!: () -> void

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_was: () -> ::String?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_previous_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_previously_was: () -> ::String?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def restore_thumbnail!: () -> void

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def clear_thumbnail_change: () -> void

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_thumbnail?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_thumbnail: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_before_last_save: () -> ::String?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_thumbnail?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_change_to_be_saved: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.binary "thumbnail"
    # ```
    #
    %a{rbs:test:target}
    def thumbnail_in_database: () -> ::String?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title: () -> ::String?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title=: (::String? value) -> void

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_before_type_cast: () -> untyped

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_for_database: () -> untyped

    # ```ruby
    # t.string "title"
    # ```
    %a{rbs:test:target}
    def title_came_from_user?: () -> bool

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title?: () -> bool

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_will_change!: () -> void

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_was: () -> ::String?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_previous_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_previously_was: () -> ::String?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def restore_title!: () -> void

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def clear_title_change: () -> void

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_title?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_title: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_before_last_save: () -> ::String?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_title?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_change_to_be_saved: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "title"
    # ```
    #
    %a{rbs:test:target}
    def title_in_database: () -> ::String?

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at=: (::ActiveSupport::TimeWithZone | ::Time value) -> void

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_for_database: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    %a{rbs:test:target}
    def updated_at_came_from_user?: () -> bool

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at?: () -> bool

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone ]?

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_will_change!: () -> void

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_was: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_previous_change: () -> [ ::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone ]?

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def restore_updated_at!: () -> void

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def clear_updated_at_change: () -> void

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_updated_at?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_updated_at: () -> [ ::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone ]?

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_updated_at?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_change_to_be_saved: () -> [ ::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone ]?

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    %a{rbs:test:target}
    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count: () -> ::Integer?

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count=: (::Integer? value) -> void

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_before_type_cast: () -> untyped

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_for_database: () -> untyped

    # ```ruby
    # t.bigint "views_count"
    # ```
    %a{rbs:test:target}
    def views_count_came_from_user?: () -> bool

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count?: () -> bool

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_change: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_will_change!: () -> void

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_was: () -> ::Integer?

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_previous_change: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_previously_was: () -> ::Integer?

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def restore_views_count!: () -> void

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def clear_views_count_change: () -> void

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_views_count?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_views_count: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_before_last_save: () -> ::Integer?

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_views_count?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_change_to_be_saved: () -> [ ::Integer?, ::Integer? ]?

    # ```ruby
    # t.bigint "views_count"
    # ```
    #
    %a{rbs:test:target}
    def views_count_in_database: () -> ::Integer?
  end
  include GeneratedAttributeMethods

  def self.create: (?body: ::String, ?created_at: ::ActiveSupport::TimeWithZone | ::Time, ?likes_count: ::Integer, ?metadata: untyped, ?price: ::BigDecimal, ?published: bool, ?published_on: ::Date, ?rating: ::Float, ?start_time: ::ActiveSupport::TimeWithZone | ::Time, ?thumbnail: ::String, ?title: ::String, ?updated_at: ::ActiveSupport::TimeWithZone | ::Time, ?views_count: ::Integer) -> instance
                 | (Array[untyped]) -> Array[instance]
end

# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "taggings", primary_key: ["post_id", "tag_id"], force: :cascade do |t|
#   t.string "context"
#   t.integer "post_id", null: false
#   t.integer "tag_id", null: false
# end
# ```
class Tagging < ::ApplicationRecord
  module GeneratedAttributeMethods
    def id: () -> Array[untyped]?

    def id=: (Array[untyped]? value) -> void

    def id_before_type_cast: () -> untyped

    def id_for_database: () -> untyped

    def id_came_from_user?: () -> bool

    def id?: () -> bool

    def id_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def id_changed?: (?from: untyped, ?to: untyped) -> bool

    def id_change: () -> [ Array[untyped]?, Array[untyped]? ]?

    def id_will_change!: () -> void

    def id_was: () -> Array[untyped]?

    def id_previous_change: () -> [ Array[untyped]?, Array[untyped]? ]?

    def id_previously_was: () -> Array[untyped]?

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def saved_change_to_id?: (?from: untyped, ?to: untyped) -> bool

    def saved_change_to_id: () -> [ Array[untyped]?, Array[untyped]? ]?

    def id_before_last_save: () -> Array[untyped]?

    def will_save_change_to_id?: (?from: untyped, ?to: untyped) -> bool

    def id_change_to_be_saved: () -> [ Array[untyped]?, Array[untyped]? ]?

    def id_in_database: () -> Array[untyped]?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context: () -> ::String?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context=: (::String? value) -> void

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_before_type_cast: () -> untyped

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_for_database: () -> untyped

    # ```ruby
    # t.string "context"
    # ```
    %a{rbs:test:target}
    def context_came_from_user?: () -> bool

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context?: () -> bool

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_will_change!: () -> void

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_was: () -> ::String?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_previous_change: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_previously_was: () -> ::String?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def restore_context!: () -> void

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def clear_context_change: () -> void

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_context?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_context: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_before_last_save: () -> ::String?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_context?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_change_to_be_saved: () -> [ ::String?, ::String? ]?

    # ```ruby
    # t.string "context"
    # ```
    #
    %a{rbs:test:target}
    def context_in_database: () -> ::String?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id: () -> ::Integer

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id=: (::Integer value) -> void

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_before_type_cast: () -> untyped

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_for_database: () -> untyped

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    %a{rbs:test:target}
    def post_id_came_from_user?: () -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id?: () -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_change: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_will_change!: () -> void

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_was: () -> ::Integer

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_previous_change: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_previously_was: () -> ::Integer

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def restore_post_id!: () -> void

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def clear_post_id_change: () -> void

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_post_id?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_post_id: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_before_last_save: () -> ::Integer

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_post_id?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_change_to_be_saved: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "post_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def post_id_in_database: () -> ::Integer

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id: () -> ::Integer

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id=: (::Integer value) -> void

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_before_type_cast: () -> untyped

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_for_database: () -> untyped

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    %a{rbs:test:target}
    def tag_id_came_from_user?: () -> bool

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id?: () -> bool

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_changed?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_change: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_will_change!: () -> void

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_was: () -> ::Integer

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_previous_change: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_previously_was: () -> ::Integer

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def restore_tag_id!: () -> void

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def clear_tag_id_change: () -> void

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_tag_id?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def saved_change_to_tag_id: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_before_last_save: () -> ::Integer

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def will_save_change_to_tag_id?: (?from: untyped, ?to: untyped) -> bool

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_change_to_be_saved: () -> [ ::Integer, ::Integer ]?

    # ```ruby
    # t.integer "tag_id", null: false
    # ```
    #
    %a{rbs:test:target}
    def tag_id_in_database: () -> ::Integer
  end
  include GeneratedAttributeMethods

  def self.create: (?context: ::String, ?post_id: ::Integer, ?tag_id: ::Integer) -> instance
                 | (Array[untyped]) -> Array[instance]
end
