#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.join(__dir__, "../lib")
require "rbs/siggen"
require "pathname"
require "optparse"

options = { sig_dirs: [], rails: false }
parser = OptionParser.new do |opts|
  opts.banner = "Usage: rbs-siggen [options] <lib-path>"

  opts.on("--sig-dir DIR", "Path to RBS signature directory (can be specified multiple times)") do |dir|
    options[:sig_dirs] << dir
  end

  opts.on("--rails", "Preset to generate signatures for Rails applications") do
    options[:rails] = true
  end

  opts.on("--siggen_dir DIR", "For debug") do |dir|
    options[:siggen_dir] = dir
  end

  opts.on("-v", "--version", "Show version") do
    puts "rbs-siggen #{RBS::Siggen::VERSION}"
    exit
  end

  opts.on("-h", "--help", "Show this help") do
    puts opts
    exit
  end
end

parser.parse!

if ARGV.empty? && !options[:rails]
  puts parser
  exit 1
end

options[:sig_dirs] = ["sig"] if options[:sig_dirs].empty?

lib_path = ARGV[0]

siggen = RBS::Siggen.new do |env_loader|
  options[:sig_dirs].each do |dir|
    env_loader.add path: Pathname(dir)
  end

  config_path = RBS::Collection::Config.find_config_path || RBS::Collection::Config::PATH
  if config_path
    lock_path = RBS::Collection::Config.to_lockfile_path(config_path)
    if lock_path.file?
      lock = RBS::Collection::Config::Lockfile.from_lockfile(
        lockfile_path: lock_path,
        data: YAML.load_file(lock_path.to_s)
      )
    end
  end
  env_loader.add_collection(lock) if lock

  if options[:rails]
    if options[:siggen_dir]
      env_loader.add path: Pathname(options[:siggen_dir])
    else
      spec = Gem::Specification.find_by_name("rbs-siggen")
      env_loader.add path: Pathname(spec.gem_dir) / "siggen"
    end
  end
end

def find_rails_root(start_dir = Dir.pwd)
  Pathname.new(start_dir).ascend do |path|
    return path if File.exist? "#{path}/config/application.rb"
  end
  nil
end

if options[:rails] && lib_path.nil?
  rails_root = find_rails_root
  if rails_root
    siggen.analyze(path: "#{rails_root}/db/schema.rb") do |siggen, _|
      puts siggen.generate
    end

    siggen.analyze(path: "#{rails_root}/app/models/") do |siggen, _|
      output = siggen.generate
      puts output unless output.empty?
    end
  end
else
  siggen.analyze(path: Pathname(lib_path)) do |siggen, _|
    puts siggen.generate
  end
end
