#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.join(__dir__, "../lib")
require "rbs/siggen"
require "pathname"
require "optparse"

options = { sig_dirs: [] }
parser = OptionParser.new do |opts|
  opts.banner = "Usage: rbs-siggen [options] <lib-path>"

  opts.on("--sig-dir DIR", "Path to RBS signature directory (can be specified multiple times)") do |dir|
    options[:sig_dirs] << dir
  end

  opts.on("-v", "--version", "Show version") do
    puts "rbs-siggen #{RBS::Siggen::VERSION}"
    exit
  end

  opts.on("-h", "--help", "Show this help") do
    puts opts
    exit
  end
end

parser.parse!

if ARGV.empty?
  puts parser
  exit 1
end

options[:sig_dirs] = ["sig", ".gem_rbs_collection"] if options[:sig_dirs].empty?

lib_path = ARGV[0]

siggen = RBS::Siggen.new do |env_loader|
  options[:sig_dirs].each do |dir|
    env_loader.add path: Pathname(dir)
  end
end
siggen.analyze(path: Pathname(lib_path)) do |siggen, _|
  puts siggen.generate
end
