#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.join(__dir__, "../lib")
require "rbs/siggen"
require "pathname"

if ARGV.empty?
  puts "rbs-siggen #{RBS::Siggen::VERSION}"
  exit 1
end

siggen = RBS::Siggen.new(path: "test/sig")
siggen.analyze(path: Pathname("test/lib")) do |siggen, path|
  puts path
  puts siggen.generate
end
